# Copyright 2025 SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Edgehog Device Runtime Proto"
SPDX-PackageDownloadLocation = "https://github.com/edgehog-device-manager/edgehog-device-runtime-proto"
