# Copyright 2024 - 2025 SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - release-*
permissions:
  contents: read
# Spend CI time only on latest ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
    working-directory: rust
jobs:
  dco:
    uses: ./.github/workflows/dco.yaml
    permissions:
      actions: read
      pull-requests: read
    with:
      pr: ${{ github.event.pull_request.number }}
  reuse:
    uses: ./.github/workflows/reuse-lint.yaml
  protobuf:
    uses: ./.github/workflows/protobuf.yaml
  warmup-caches:
    uses: ./.github/workflows/warmup-caches.yaml
    needs: [reuse, dco]
  codegen:
    uses: ./.github/workflows/codegen.yaml
    needs: [warmup-caches]
  rust-check:
    uses: ./.github/workflows/rust-check.yaml
    needs: [warmup-caches]
  rust-test:
    uses: ./.github/workflows/rust-test.yaml
    secrets: inherit
    needs: [warmup-caches]
