# Copyright 2025 SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

name: publish
# When a release is published or called manually
on:
  release:
    types:
      - published
  workflow_dispatch:
# Only needs to clone the repository
permissions:
  contents: read
# Safer shell
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  # It's not safe to cancel the publish
  cancel-in-progress: false
env:
  CARGO_TERM_COLOR: always
jobs:
  publish:
    name: stable / publish
    needs: [for-publish]
    runs-on: ubuntu-24.04
    steps:
      - uses: ./.github/actions/install-deps
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
      - name: publish creates
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        # Publish the crates in order of dependency
        run: |
          cargo publish --locked -p edgehog-device-runtim-proto
